### PR TITLE
Revert "ci: Allow ci to skip running if only specific files are changed"

### PR DESCRIPTION
**Pull request by sithlord48**
This reverts commit 14dfcb672d4225d30d1b29c6cf6e80ff5e6a43e3.
If  #7662 can not correct the start issue

### CODE REVIEW

**Comment by sithlord48** [comment]
We can't land our changes without CI passing and there is no consideration for skipped CI :(

**Review by nbolton — APPROVED** [review]

**Comment by nbolton** [comment]
> We can't land our changes without CI passing and there is no consideration for skipped CI :(

Ah of course. Didn't think of that. I bet we can pass CI if only certain files are changed through a bash step or something. Might be a bit less clean though. Worth doing do you think?

**Comment by sithlord48** [comment]
Yeah ill just drop that that check for now and ill add it back when we find the right combo or rules / overrides so we can land those w/o CI

**Comment by sithlord48** [comment]
Fixed by #7662

**Pull request closed without merging**
