### PR TITLE
Use #pragma once for headers

### PR DESCRIPTION
**Pull request by sithlord48**
use #pragma once for all headers.

### CODE REVIEW

**Comment by nbolton** [comment]
Oh this is wonderful. I have been meaning to get round to this for a while now, so I'm glad to see this PR. Thank you. I'll try to get to my laptop to approve soon unless @shymega beats me to it.

**Review by shymega — APPROVED** [review]
LGTM. Much simpler than negating booleans.

**Comment by shymega** [comment]
@nbolton The auto-merge requires one more approving review.

**Comment by nbolton** [comment]
> @nbolton The auto-merge requires one more approving review.

Oh. I thought we set this to 1 review required. Was it changed? You should be able to see the branch protection settings. I'm on holiday at the moment so a bit tricky for me to check but I can take a look later on my laptop.

**Review by nbolton — APPROVED** [review]

**Pull request merged**
