### PR TITLE
Fixed UTF-16 surrogate handling

### PR DESCRIPTION
**Pull request by pedronavf**
The data pointer needs to move before decoding the second surrogate, and not after. Because of this the first surrogate was begin decoded again, resulting in an invalid codepoint.

This affected clipboard operations originating on Windows machines, where the text in CF_UNICODE is encoded in UTF-16 and copying characters from a high plane (like emojis) was broken.

### CODE REVIEW

**Comment by sithlord48** [comment]
could you please change the commit message to use `fix:` instead of `Fixed` this will make sure its picked up by the auto notes generated on release.

**Comment by pedronavf** [comment]
@sithlord48 done!

**Comment by sithlord48** [comment]
Possible solution for : #7961  #7789

**Review by sithlord48 — APPROVED** [review]
:+1:

**Comment by sithlord48** [comment]
@pedronavf  i will take over any needed updates for this PR until it lands. So no need to worry about doing rebases.

**Comment by nbolton** [comment]
> This affected clipboard operations originating on Windows machines, where the text in CF_UNICODE is encoded in UTF-16 and copying characters from a high plane (like emojis) was broken.

Do you have steps to repro the bug? On `master` I am able to copy emojis to and from a Windows client.

**Comment by pedronavf** [comment]
> > This affected clipboard operations originating on Windows machines, where the text in CF_UNICODE is encoded in UTF-16 and copying characters from a high plane (like emojis) was broken.
> 
> Do you have steps to repro the bug? On `master` I am able to copy emojis to and from a Windows client.

You need to copy an emoji from a Unicode high plane (like U+1F600), where the use of UTF-16 surrogate pairs is necessary.

Try to copy the emoji from this page: https://graphemica.com/1F600

**Comment by nbolton** [comment]
Tested and working. Thanks for the PR.

Before: Copied 😀 (09 08 00 00) from Windows client to macOS client, resulted in � (FD FF 00 00)
After: Copied 😀 (09 08 00 00) from Windows client to macOS client and result was 😀 (09 08 00 00)

Also works the opposite way round (macOS to Windows) and also when Windows is server.

**Pull request merged**
