### PR TITLE
Use Cpack for Mac os

### PR DESCRIPTION
**Pull request by sithlord48**
- Make the App bundle using cmake
 - Make the DMG with cpack
 - Move more of the packaging.cmake into deployment

### CODE REVIEW

**Comment by nbolton** [comment]
Minor nits:
- Looks like the window is too big or the background is too small
- I'm not sure if it was like that before, but the logo in the top left looks a tad blurry ([assets](https://github.com/deskflow/deskflow-artwork/tree/main/dist/mac))

Screenshot 2024-11-20 at 08 52 16

**Comment by sithlord48** [comment]
> Minor nits:
> 
>     * Looks like the window is too big or the background is too small (white bar at the bottom)
> 
>     * I'm not sure if it was like that before, but the logo in the top left looks a tad blurry ([assets](https://github.com/deskflow/deskflow-artwork/tree/9cb3152ea41f1abdb6645741816695b00198d68a/dist/mac))
> 
> 
> Screenshot 2024-11-20 at 08 52 16

The background and window size is the same as it was before . i forgot to tell it to turn the bottom bar off (mine is on) ill fix that soon

**Comment by eduardo-publi** [comment]
Just upgraded to 1.17.2 for arm64 macOS 15.1.1 (client) and server (win11-23h2) and now Im getting error:
ERROR: failed to create quartz event tap
Entering and leaving screen events are captured accordingly (no network errors about new os controls),  but mouse moving and keystrokes does not flowing from server to client... May this PR  solve this issue?

**Comment by sithlord48** [comment]
> Just upgraded to 1.17.2 for arm64 macOS 15.1.1 (client) and server (win11-23h2) and now Im getting error: ERROR: failed to create quartz event tap Entering and leaving screen events are captured accordingly (no network errors about new os controls), but mouse moving and keystrokes does not flowing from server to client... May this PR solve this issue?

no this only moves our packaging to use cpack and not an external script

**Review by nbolton — APPROVED** [review]

**Comment by nbolton** [comment]
Looks good now!

Screenshot 2024-11-21 at 14 26 46

**Pull request merged**
