### PR TITLE
Increase NumButtonIDs to 7, to support mice with more buttons

### PR DESCRIPTION
**Pull request by dkniffin**
[Maybe] fixes: #58

### CODE REVIEW

**Comment by dkniffin** [comment]
@nbolton I was able to install the build artifacts on server and client and got them connected. It didn't resolve the issue, but now when I press one of the two buttons, I get the following error on the server: 
```
[2024-10-16T17:10:10] ERROR: tls error occurred (generic failure)
[2024-10-16T17:10:10] ERROR: openssl error: error:0A000126:SSL routines::unexpected eof while reading
```
and this error on the client:
```
[2024-10-16T17:10:10] WARNING: desktop process exited with error code: 4
```

any ideas?

**Comment by nbolton** [comment]
> [2024-10-16T17:10:10] ERROR: tls error occurred (generic failure)
> [2024-10-16T17:10:10] ERROR: openssl error: error:0A000126:SSL routines::unexpected eof while reading

That's funny, literally just talking about that in: #7688

I think it might be unrelated to your change though and just a random bug.

> [2024-10-16T17:10:10] WARNING: desktop process exited with error code: 4

Might need a bit more context. Could you turn up the logging to debug?

**Comment by dkniffin** [comment]
I turned it up to debug1, and I see this:
```
[2024-10-16T17:20:48] DEBUG1: recv mouse down id=1
[2024-10-16T17:20:48] DEBUG1: faking mouse button id: 0 press: pressed
[2024-10-16T17:20:49] DEBUG1: recv mouse up id=1
[2024-10-16T17:20:49] DEBUG1: faking mouse button id: 0 press: released
[2024-10-16T17:20:51] DEBUG1: recv mouse down id=7
[2024-10-16T17:20:51] DEBUG1: faking mouse button id: 6 press: pressed
[2024-10-16T17:20:51] WARNING: desktop process exited with error code: 4
```

So I guess it's faking it successfully now, but somehow that's causing a crash.

**Comment by dkniffin** [comment]
Maybe a new item needs to be added in [here](https://github.com/deskflow/deskflow/blob/52f616a15d094bb3ba7ec30a2a04b764f7b2bf22/src/lib/platform/OSXScreen.mm#L448-L454)?

**Comment by nbolton** [comment]
> Maybe a new item needs to be added in [here](https://github.com/deskflow/deskflow/blob/52f616a15d094bb3ba7ec30a2a04b764f7b2bf22/src/lib/platform/OSXScreen.mm#L448-L454)?
> 
> Edit: I'm thinking that because I suspect an out-of-bounds error [here](https://github.com/deskflow/deskflow/blob/52f616a15d094bb3ba7ec30a2a04b764f7b2bf22/src/lib/platform/OSXScreen.mm#L590)

Those lines do look related. I'm sure there's somewhere else that mouse buttons are defined but I'd need to dig.

**Comment by nbolton** [comment]
@sithlord48 Aha, I think our branch protection rules (linear history) can only apply to _our_ branches in _our_ repo, i.e. not PRs from external branches. I just tried the merge button out of curiosity, and it allowed it, which makes sense since `dkniffin:increase-numbuttonids` is not under our control.

**Comment by dkniffin** [comment]
Another question/concern I have about this, is how to know which button IDs are which? Do all mice transmit the same button event IDs? It seems no, since mine uses 4 and 5 for the scroll wheel. Is there a way to get a consistent behavior with that?

**Comment by nbolton** [comment]
> Another question/concern I have about this, is how to know which button IDs are which? Do all mice transmit the same button event IDs? 

Deskflow listens to the OS API, not the mouse, so it's down to the OS.

> It seems no, since mine uses 4 and 5 for the scroll wheel. Is there a way to get a consistent behavior with that?

I'm not sure. I wonder if the OS API docs might reveal something?

**Comment by dkniffin** [comment]
This didn't fix the issue, and I don't have more time to troubleshoot

**Pull request closed without merging**
